'''
code is copied from:
https://www.askpython.com/python/examples/generate-random-strings-in-python

numbers generated by a random module will generate a character
from ASCII table. chr(65) will be a capital letter A.

numbers are between 48 and 58
uppercase letters are between 65 and 65 + 26
lowercase letters are between 96 and 96 + 26

full ASCII table have 255 characters
'''

import random
 
random_string = ''
 
for _ in range(10):
    # Considering only upper and lowercase letters
    random_integer = random.randint(97, 97 + 26 - 1)
    flip_bit = random.randint(0, 1)
    # Convert to lowercase if the flip bit is 1
    random_integer = random_integer - 32 if flip_bit == 1 else random_integer
    # Keep appending random characters using chr(x)
    random_string += (chr(random_integer))
 
print(random_string, len(random_string))

'''
useful links:
https://geekflare.com/password-generator-python-code/
https://www.askpython.com/python/examples/generate-random-strings-in-python
https://docs.python.org/3.3/library/random.html
https://docs.python.org/3.3/library/string.html
'''

#modules: random, string
#tags: randint(), ascii, chr(), password generator